version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5984/_up" ]
      interval: 10s
      retries: 5

  init_couchdb:
    image: curlimages/curl
    volumes:
      - ./couchdb/init_couchdb.sh:/init_couchdb.sh
    entrypoint: ["sh", "/init_couchdb.sh"]
    depends_on:
      couchdb:
        condition: service_healthy

  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - COUCHDB_SERVER=http://localhost:5984/
      - COUCHDB_DATABASE=insulin-database
    depends_on:
      couchdb:
        condition: service_completed_successfully

volumes:
  couchdb_data: